#!/bin/bash
# Author : Renan Fargetton 2012-2022
# Licence : GNU GPL v3 or later

#path="/sys/class/backlight/intel_backlight"
backlight_path=$(readlink -f /sys/class/backlight/*/)
# alternative interface (0 < x < 10)
#backlight_path="/sys/class/backlight/acpi_video0/"

# max should be 4296
max=$(cat ${backlight_path}/max_brightness)
# step: represent the difference between previous and next brightness
step=$(($max/10))
# for a value smaller than treshold, the steps are smaller for a more accurate setting at low intensity
treshold=$((2*$step))
previous=$(cat ${backlight_path}/brightness)

function commit {
	if [[ $1 = [0-9]* ]]
	then 
		if [[ $1 -gt $max ]]
		then 
			next=$max
		elif [[ $1 -lt 0 ]]
		then 
			next=0
		else 
			next=$1
		fi
		echo $next >> ${backlight_path}/brightness
		exit 0
	else 
		exit 1
	fi
}

case "$1" in
 up)
	if [[ $previous -le $treshold ]]
		then 
			step=$(($previous/4))
			if [[ $previous -le 4 ]] ; then step=1 ; fi
	fi
	 commit $(($previous + $step))
   ;;
 down)
	if [[ $previous -le $treshold ]]
		then 
			step=$(($previous/4));
			if [[ $previous -le 4 ]] ; then step=1 ; fi
	fi
	commit $(($previous - $step))
   ;;
 max)
	 commit $max
   ;;
 off)
	 commit 0
   ;;
 show)
	 echo $previous
   ;;
 night)
	 commit $(($max/4)) 
 	 ;;
 allowusers)
	 # Allow members of users group to change brightness
	 sudo /usr/bin/chgrp users ${backlight_path}/brightness
	 sudo /usr/bin/chmod g+w ${backlight_path}/brightness
   ;;
 u)
	 $0 allowusers
   ;;
 disallowusers)
	 # Allow members of users group to change brightness
	 sudo /usr/bin/chgrp root ${backlight_path}/brightness
	 sudo /usr/bin/chmod g-w ${backlight_path}/brightness
   ;;
 *)
	 commit	$1
esac

exit 0

